### PR TITLE
issue-6: added new feature:  getAttributes

### PR DESCRIPTION
**Pull request by ericbroda**
Added feature:  "getAttributes" to select multiple attributes in a single call.

Addresses issue #6

### CODE REVIEW

**Comment by zuazo** [comment]
@ericbroda, thanks for the PR!! :smiley:

Can you fix the failing test and update the README?

The error in Travis CI:

```
  75 passing (4s)
  1 failing

  1) MBeanServerConnection #getAttribute:
  AssertionError: ["javax.management.ObjectName","[Ljava.lang.String;"] deepEqual ["javax.management.ObjectName","java.lang.String"]
      at MBeanServerConnection.method (/home/travis/build/onddo/node-jmx/test/adapters/mbeanServerConnection.js:183:14)
      at JavaReflection.mbeanServerConnection.javaReflection.invokeMethod (/home/travis/build/onddo/node-jmx/test/adapters/mbeanServerConnection.js:173:16)
      at MBeanServerConnection.getAttribute (/home/travis/build/onddo/node-jmx/lib/adapters/mbeanServerConnection.js:102:23)
      at testReflectionCall (/home/travis/build/onddo/node-jmx/test/adapters/mbeanServerConnection.js:175:35)
      at Context.method (/home/travis/build/onddo/node-jmx/test/adapters/mbeanServerConnection.js:182:5)
      at Test.Runnable.run (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runnable.js:217:15)
      at Runner.runTest (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:373:10)
      at Runner.runTests.next (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:451:12)
      at next (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:298:14)
      at Runner.hooks (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:308:7)
      at next (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:246:23)
      at Runner.hook (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:270:7)
      at done (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runnable.js:206:5)
      at callFn (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runnable.js:261:7)
      at Hook.Runnable.run (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runnable.js:243:7)
      at next (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:258:10)
      at Runner.hook (/home/travis/build/onddo/node-jmx/node_modules/mocha/lib/runner.js:275:5)
      at process.startup.processNextTick.process._tickCallback (node.js:245:9)

make[2]: *** [mocha] Error 1
make[2]: Leaving directory `/home/travis/build/onddo/node-jmx'
make[1]: *** [test-no-coveralls] Error 2
make[1]: Leaving directory `/home/travis/build/onddo/node-jmx'
make: *** [test] Error 2

npm ERR! weird error 2
npm ERR! not ok code 0
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by ericbroda** [comment]
@zuazo, I made the changes to the README and managed to fix the majority of test cases, however, there is one remaining error in test cases:

`Uncaught Error: Error running instance method
java.lang.IllegalArgumentException: argument type mismatch`

I have spent a few days on this one item and I would like to *humbly* ask for your assistance in figuring out what I need to do to fix this one remaining test error.  I will be happy to fix the remaining errors if you may be able to provide some guidance.

(Note:  I know the code does actually work as I can run it successfully - it is just the test cases that seem to be causing the issue)

**Comment by zuazo** [comment]
Merged in master manually. The fix in 4b89b122019d9469d006bc9b1ae71ead883e2cb9 and an improvement in 110d0ed83b636d87cc691603e2cadb5fc097e928.

Thanks for all your fantastic work @ericbroda. The PR you made is really hard to do. :wink:

**Comment by zuazo** [comment]
Released in [`0.4.0`](https://github.com/onddo/node-jmx/releases/tag/0.4.0).

**Pull request merged**
